FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf

COPY frontend/index.html /usr/share/nginx/html/
COPY frontend/deals.html /usr/share/nginx/html/
COPY frontend/deals/ /usr/share/nginx/html/deals/
COPY frontend/shared/ /usr/share/nginx/html/shared/