FROM golang:1.21.6-alpine3.19 AS builder

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main cmd/api/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
RUN addgroup -g 65532 nonroot &&\
    adduser -D -u 65532 -G nonroot nonroot
WORKDIR /root/
COPY --from=builder /app/main .
RUN chown -R nonroot:nonroot /root/
USER nonroot
EXPOSE 300
CMD ["./main"]